# Generated by Django 4.0.5 on 2022-08-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='chinese_title',
            new_name='discount_code',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='advertisement_end_date',
            new_name='discount_end_date',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='company_name',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='customer_name',
            new_name='discount_reduce_amount',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='advertisement_start_date',
            new_name='discount_start_date',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='english_title',
            new_name='promotion_name',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='advertisement_active',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='advertisement_image',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='advertisement_link',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='advertisement_payment_method',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='advertisement_price',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='advertisement_price_currency',
        ),
    ]
