# Generated by Django 4.0.5 on 2022-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_rename_chinese_title_discount_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_percentage_value',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_reduce_amount_value',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_reduce_amount',
            field=models.BooleanField(),
        ),
    ]
