# Generated by Django 4.0.5 on 2022-08-09 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discount_discount_percentage_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_reduce_amount_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
