# Generated by Django 3.2.14 on 2022-07-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('description', models.CharField(max_length=500)),
                ('uid', models.UUIDField(blank=True, default=None, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
