# Generated by Django 3.2.14 on 2022-07-06 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('chinese_name', models.CharField(max_length=500)),
                ('english_name', models.CharField(max_length=500)),
                ('region_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
