# Generated by Django 3.2.14 on 2022-07-06 09:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=500)),
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region')),
            ],
        ),
    ]
