# Generated by Django 3.2.14 on 2022-07-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_auto_20220706_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='newusers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='newusers',
            name='user_permissions',
        ),
    ]
