# Generated by Django 3.2.14 on 2022-07-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_auto_20220706_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUsers',
        ),
    ]
